env:
  es2017: true
  browser: true
  commonjs: true

extends: [
  'eslint:recommended',
  'plugin:react/recommended',
  'plugin:@typescript-eslint/eslint-recommended',
  'plugin:@typescript-eslint/recommended',
]

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins: ['react', '@typescript-eslint']

settings:
  react:
    version: '16'
